server:
  port: 8080
 
spring:
  application:
    name: store-api
  datasource:
    url: jdbc:h2:mem:storedb
    driver-class-name: org.h2.Driver
    username: sa
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false                                 #disable Hibernate logs (keep only logger)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false

logging:
  level:
    root: INFO
    com.store: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level){faint,blue,green,yellow,red} [%X{requestId}] [%thread] %logger{36} - %msg%n"
  ch.qos.logback.core.ConsoleAppender:
    withJansi: true 